### ISSUE TITLE
Ftm strats needs to open to ftm explorer

### ISSUE THREAD

**Issue by DarkGhost7** [Major-Eth/The-Vaults-at-Yearn#2]
Fantom strategy links currently opens to etherscan need to switch to https://ftmscan.com

**Comment by DarkGhost7** [comment]
This is only for https://strats-watch.vercel.app/internal/missing-descriptions

**Comment by Major-Eth** [comment]
Fixed with commit [f350058321b1f082cd97a0fc5caadac52128397f](https://github.com/Major-Eth/The-Vaults-at-Yearn/commit/f350058321b1f082cd97a0fc5caadac52128397f)
