### ISSUE TITLE
Curve strats boost icon not showing up 

### ISSUE THREAD

**Issue by DarkGhost7** [Major-Eth/The-Vaults-at-Yearn#3]
we say in the copy for yearn and curve synergy
![image](https://user-images.githubusercontent.com/38810205/147253248-e80d6545-dba6-4a66-85f3-320473424fb9.png)

But I don't see the boost icon by the strategies. Maybe we can get it to auto add to all Curve Boost and Convex Reinvest strategies.

**Comment by Major-Eth** [comment]
Fixed with commit [19cb011fbeca2ba5de035e96174fa89339f76ca2](https://github.com/Major-Eth/The-Vaults-at-Yearn/commit/19cb011fbeca2ba5de035e96174fa89339f76ca2)
