### ISSUE TITLE
Make all retired vaults images the same

### ISSUE THREAD

**Issue by DarkGhost7** [Major-Eth/The-Vaults-at-Yearn#4]
![image](https://user-images.githubusercontent.com/38810205/147275904-1b12d691-40f5-4b61-9dd7-889c1198b97b.png)
All retired vaults should show this image and not the regular vault image to further reinforce the idea that they need to migrate their funds. v1 vaults still show the regular icons.

**Comment by Major-Eth** [comment]
Fixed by commit [ea1dd169493bb742c910631ac8319339bd41020c](https://github.com/Major-Eth/The-Vaults-at-Yearn/commit/ea1dd169493bb742c910631ac8319339bd41020c)
