### ISSUE TITLE
Retired vaults shouldnt show boost icon

### ISSUE THREAD

**Issue by DarkGhost7** [Major-Eth/The-Vaults-at-Yearn#5]
![image](https://user-images.githubusercontent.com/38810205/147276039-467c5cc8-9b9a-4c71-928f-15af3d7b138c.png)
Since they are no longer working they are not boosted

**Comment by Major-Eth** [comment]
Fixed by commit [705e7f6630c1241bf4d77280c5f1ee7544a2f9dc](https://github.com/Major-Eth/The-Vaults-at-Yearn/commit/705e7f6630c1241bf4d77280c5f1ee7544a2f9dc)
